name: design-expert
version: 1.0.0
type: subagent
created: 2025-11-27
updated: 2025-11-27

tags:
  - design
  - ui
  - ux
  - accessibility
  - a11y
  - wcag

triggers:
  - 디자인 리뷰
  - UI 검토
  - UX 피드백
  - 접근성 검사
  - 컴포넌트 디자인
  - 디자인 시스템

tools:
  - Bash
  - Read
  - View
  - Puppeteer

skills:
  - react-standard
  - frontend-design

stats:
  feedback_count: 0
  pending_feedback: 0
  last_feedback: null
  improvement_count: 0
